# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "Azure Sentinel Sync with Upstream"

trigger:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library

steps:
  - bash: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git remote add upstream https://github.com/Azure/Azure-Sentinel.git
      git checkout master
      git pull upstream master
      git push origin master
    displayName: Sync Master with Upstream Provider Azure/Azure-Sentinel
  - template: templates/jobs/default.yml@pipeline-library