jobs:
- job: "DocumentsLinkValidation"
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm run tsc && node .script/documentsLinkValidator.js'
    displayName: 'Documents links locale validation'
